use {
    nanoid::nanoid,
    pdb::FallibleIterator,
    std::{fs::File, io::Write},
};

pub fn path_exists(path: &str) -> bool {
    std::fs::metadata(path).is_ok()
}

pub fn pdb_dump(pdb_path: String, file_type: String, mut dump_file: File) -> pdb::Result<()> {
    write!(
        dump_file,
        "/*###############################################################\
    \nBDS function symbols and RVAs\
    \nFile generated by BDumper, a rust bds pdb dumper made by Luke7720\
    \n###############################################################*/\n"
    )
        .expect("ERROR: Could not write to file");

    let char_list: [char; 53] = [
        'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r',
        's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '_', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I',
        'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z',
    ];

    let file_path = File::open(&pdb_path)?;
    let mut pdb = pdb::PDB::open(file_path)?;

    let symbol_table = pdb.global_symbols()?;
    let address_map = pdb.address_map()?;

    let mut symbols = symbol_table.iter();
    while let Some(symbol) = symbols.next()? {
        match symbol.parse() {
            Ok(pdb::SymbolData::Public(data)) if data.function => {
                let rva = data.offset.to_rva(&address_map).unwrap_or_default();
                if file_type == ".txt" {
                    write!(dump_file, "{}\n{}\n\n", data.name, rva)
                        .expect("ERROR: Could not write to file");
                } else if file_type == ".hpp" {
                    let fn_id = nanoid!(10, &char_list);
                    write!(
                        dump_file,
                        "//{};\nconstexpr unsigned int {} = {};\n\n",
                        data.name, fn_id, rva
                    )
                        .expect("ERROR: Could not write to file");
                } else {
                    break;
                }
            }
            _ => {}
        }
    }

    nwg::simple_message("Completed", &format!("Completed dumping {}", pdb_path));
    Ok(())
}